/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blade;

import org.junit.Test;
import static org.junit.Assert.*;

import com.shreerama.mblade.service.ProjectServiceImpl;

public class AppTest {
  

    @Test public void testTrue() {
        assertTrue(true);
    }
}
